### PR TITLE
chore(CHANGELOG): update to v4.12.0

### PR DESCRIPTION
**Pull request by smbea**

### CODE REVIEW

**Review by nikku — APPROVED** [review]

**Comment by pinussilvestrus** [comment]
Do we use the Camunda Modeler versions for versioning the helpers as well? At least I didn't know about it 😄

**Comment by pinussilvestrus** [comment]
Apparently we do: https://github.com/camunda/camunda-modeler-plugin-helpers/tags
Nice 👍

**Comment by nikku** [comment]
And it makes sense, too, right? 

I'm building my app towards a certain version of the Camunda Modeler.

**Comment by pinussilvestrus** [comment]
Absolutely 👍

**Pull request merged**
