### PR TITLE
feat: add platform specific registration helpers

### LINKED ISSUE #20: Create new plugin helpers to register C7 and C8 specific plugins
__Is your feature request related to a problem? Please describe.__

To abstract away the specific keys we will use to identify C7 and C8 plugins, and make life simpler for plugin developers, we should create new plugin registrations helper functions for:

- C7 bpmn
- C8 bpmn
- C7 moddle
- C8 moddle

__Describe the solution you'd like__

Keep the old registration methods for backward compatibility, create some new ones for allowing differentiation between C7 and C8 plugins.

__Describe alternatives you've considered__

Removing the old ones and proceeding with new ones, but this would break too many things and make plugin developers have to choose between supporting modeler 4 and 5

### PR DESCRIPTION
**Pull request by Skaiir**
Closes #20

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
Do we wait for reviewing this until we implemented these new keys via https://github.com/camunda/camunda-modeler/issues/2777?

**Comment by barmac** [comment]
I guess we don't want to merge new helpers until we are settled on how they work with Camunda Modeler. @Skaiir I'd appreciate a plugin example which allows to verify the solution e2e.

**Comment by Skaiir** [comment]
@barmac I intend to make changes where required for us. I'll send over some example, it's all rather simple though :).

This can go through, people will be able to use the extensions without success but I'll need a release on this to upgrade our current plugins.

**Comment by pinussilvestrus** [comment]
Note that you don't have to release a new version to try the new helpers out. Local linking should be fine, too, I did it myself while reviewing the Modeler part: https://github.com/camunda/camunda-modeler/pull/2801#discussion_r818801577

```
cd camunda-modeler-plugin-helpers
npm link
cd my-whatever-plugin
npm link camunda-modeler-plugin-helpers
```

**Comment by Skaiir** [comment]
Yes I'm aware but part of my scope is to upgrade all camunda plugins where relevant.

**Comment by pinussilvestrus** [comment]
Yeah for making the final upgrades of course 👍

**Review by barmac — APPROVED** [review]

**Pull request merged**
